config/routes.rb
Rails.application.routes.draw do
  get 'home/zipcode'
  root 'home#index'

  post "zipcode" => 'home#zipcode'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    require 'net/http'
    require 'json'

    @url = 'https://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=60610&distance=25&API_KEY=2ECB1EAB-6356-4FFD-A1D5-6CB0990784E4'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @output = JSON.parse(@response)

    #Check for empty return value from API
    if @output.empty?
      @final_output = "Error"
    elsif !@output
      @final_output = "Error"
    else
      @final_output = @output[0]['AQI']
    end

    if @final_output == "Error"
      @api_color = "error"
    elsif @final_output <= 50
      @api_color = "good"
      @api_description = "0-50. Good."
    elsif @final_output >= 51 && @final_output <= 100
      @api_color = "moderate"
      @api_description = "51-100. Moderate."
    elsif @final_output >= 101 && @final_output <= 150
      @api_color = "usg"
      @api_description = "101-150. Unhealthy for Sensitive Groups (USG)."
    elsif @final_output >= 151 && @final_output <= 200
      @api_color = "unhealthy"
      @api_description = "151-200. Unhealthy."
    elsif @final_output >= 201 && @final_output <= 300
      @api_color = "veryunhealthy"
      @api_description = "201-300. Very Unhealthy."
    elsif @final_output >= 301 && @final_output <= 500
      @api_color = "hazardous"
      @api_description = "301-500. Hazardous."
    end

  end

  def zipcode
    @zip_query = params[:zipcode]
    if params[:zipcode] == ""
      @zip_query = "Hello, you forgot to enter a "
    elsif params[:zipcode]
      #do API stuff

      require 'net/http'
      require 'json'
  
      @url = 'https://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=' + @zip_query + '&distance=0&API_KEY=2ECB1EAB-6356-4FFD-A1D5-6CB0990784E4'
      @uri = URI(@url)
      @response = Net::HTTP.get(@uri)
      @output = JSON.parse(@response)
  
      #Check for empty return value from API
      if @output.empty?
        @final_output = "Error"
      elsif !@output
        @final_output = "Error"
      else
        @final_output = @output[0]['AQI']
      end
  
      if @final_output == "Error"
        @api_color = "error"
      elsif @final_output <= 50
        @api_color = "good"
        @api_description = "0-50. Good."
      elsif @final_output >= 51 && @final_output <= 100
        @api_color = "moderate"
        @api_description = "51-100. Moderate."
      elsif @final_output >= 101 && @final_output <= 150
        @api_color = "usg"
        @api_description = "101-150. Unhealthy for Sensitive Groups (USG)."
      elsif @final_output >= 151 && @final_output <= 200
        @api_color = "unhealthy"
        @api_description = "151-200. Unhealthy."
      elsif @final_output >= 201 && @final_output <= 300
        @api_color = "veryunhealthy"
        @api_description = "201-300. Very Unhealthy."
      elsif @final_output >= 301 && @final_output <= 500
        @api_color = "hazardous"
        @api_description = "301-500. Hazardous."
      end
    
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <%= link_to 'Ozone Inspirasi', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <%= form_tag zipcode_path, :method => 'POST' do %>
      </ul>
      <div class="d-flex">
        <%= text_field_tag 'zipcode', nil, placeholder: "Search Zipcode", class: "form-control me-2"  %>
        <%= submit_tag 'Search', class: "btn btn-outline-secondary" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<div class="jumbotron <%= @api_color %> ">
  <h1 class="display-4">Ozone Inspirasi</h1>
  <p class="lead">Your Real Time Air Quality Information Application</p>
  <br/>
  <h2 class="display-2"><%= @final_output %></h2>
  <p class="lead">This is the Air Quality Index in Your Selected Place.</p>
  <p> <%= @api_description %> </p>
  <hr class="my-4">
  <p>Hit "Refresh" in your web browser to update the reading</p>
  <br/>
</div>

app/views/home/zipcode.html.erb
<div class="jumbotron <%= @api_color %> ">
  <h1 class="display-4">Ozone Inspirasi</h1>
  <p class="lead">Your Real Time Air Quality Information Application</p>
  <br/>
  <h2 class="display-2"><%= @final_output %></h2>
  <p class="lead">This is the Air Quality Index in Your Selected Place <br/> <%= @zip_query %> zipcode </p>
  <p> <%= @api_description %> </p>
  <hr class="my-4">
  <p>Hit "Refresh" in your web browser to update the reading</p>
  <br/>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ozone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/navbar' %>
    <div class="container">
      <br/>
      <%= yield %>
    </div>
  </body>
</html>